import { useMemo, useState } from 'react';
import { useDataShare } from '../hooks/useDataShare';

const SIM_EMPTY = { phoneNumber: '', label: '', groupName: '', activeFromDay: '', activeToDay: '', dailyLimitMb: 5120, monthlyShareLimit: 10, defaultReloadData: '', defaultReloadCost: '', defaultReloadValidity: '', defaultReloadExpiresAfterDays: '', simBalance: '', status: 'active', note: '' };
const BATCH_EMPTY = { dataShareSimId: '', totalData: '', totalCost: '', validity: '', expiresAt: '', status: 'active', note: '' };
const input = 'w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm outline-none focus:border-orange-400 focus:ring-2 focus:ring-orange-100';

function money(value) { return `₦${Number(value ?? 0).toLocaleString()}`; }
function date(value) { if (!value) return '—'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleString(); }
function pct(used, total) { return total > 0 ? Math.min(100, Math.round((Number(used) / Number(total)) * 100)) : 0; }
function compact(value) { return value == null || value === '' ? '—' : value; }

function Badge({ value }) {
  const color = { active: 'bg-emerald-100 text-emerald-700', matched: 'bg-emerald-100 text-emerald-700', paused: 'bg-amber-100 text-amber-700', exhausted: 'bg-slate-100 text-slate-600', expired: 'bg-slate-100 text-slate-600', retired: 'bg-slate-100 text-slate-600', disabled: 'bg-slate-100 text-slate-600', unmatched: 'bg-red-100 text-red-700', lookup_failed: 'bg-orange-100 text-orange-700' }[value] ?? 'bg-slate-100 text-slate-600';
  return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${color}`}>{String(value ?? 'unknown').replace('_', ' ')}</span>;
}

function Progress({ value, max, warning }) {
  const percent = pct(value, max);
  return <div className="min-w-32"><div className="mb-1 flex justify-between text-xs text-gray-500"><span>{Number(value ?? 0).toLocaleString()} / {Number(max ?? 0).toLocaleString()}</span><span>{percent}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-gray-100"><div className={`h-full rounded-full ${warning || percent >= 100 ? 'bg-red-500' : 'bg-orange-500'}`} style={{ width: `${percent}%` }} /></div></div>;
}

function Modal({ title, children, onClose }) {
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold text-gray-900">{title}</h2><button onClick={onClose} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100" aria-label="Close">✕</button></div>{children}</div></div>;
}

function Field({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-500">{label}</span>{children}</label>; }

function SimForm({ initial, onSubmit, onClose }) {
  const [form, setForm] = useState({ ...SIM_EMPTY, ...initial });
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const set = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { const allowed = ['phoneNumber','label','groupName','activeFromDay','activeToDay','dailyLimitMb','monthlyShareLimit','defaultReloadData','defaultReloadCost','defaultReloadValidity','defaultReloadExpiresAfterDays','simBalance','status','note']; const numeric = ['activeFromDay','activeToDay','dailyLimitMb','monthlyShareLimit','defaultReloadCost','defaultReloadExpiresAfterDays','simBalance']; const body = Object.fromEntries(allowed.filter((key) => form[key] !== '').map((key) => [key, numeric.includes(key) ? Number(form[key]) : form[key]])); await onSubmit(body); onClose(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  return <form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2">
    <Field label="Phone number *"><input required disabled={Boolean(initial?.id)} value={form.phoneNumber} onChange={(e) => set('phoneNumber', e.target.value)} className={input} placeholder="2348160424228" /></Field>
    <Field label="Friendly label"><input value={form.label} onChange={(e) => set('label', e.target.value)} className={input} placeholder="SIM A1" /></Field>
    <Field label="Group"><input value={form.groupName} onChange={(e) => set('groupName', e.target.value)} className={input} placeholder="Group A" /></Field>
    <Field label="Status"><select value={form.status} onChange={(e) => set('status', e.target.value)} className={input}><option>active</option><option>paused</option><option>retired</option></select></Field>
    <Field label="Active from day"><input type="number" min="1" max="31" value={form.activeFromDay} onChange={(e) => set('activeFromDay', e.target.value)} className={input} /></Field>
    <Field label="Active to day"><input type="number" min="1" max="31" value={form.activeToDay} onChange={(e) => set('activeToDay', e.target.value)} className={input} /></Field>
    <Field label="Daily limit (MB)"><input type="number" min="0" value={form.dailyLimitMb} onChange={(e) => set('dailyLimitMb', e.target.value)} className={input} /></Field>
    <Field label="Monthly share limit"><input type="number" min="0" value={form.monthlyShareLimit} onChange={(e) => set('monthlyShareLimit', e.target.value)} className={input} /></Field>
    <Field label="Default reload data"><input value={form.defaultReloadData} onChange={(e) => set('defaultReloadData', e.target.value)} className={input} placeholder="11GB" /></Field>
    <Field label="Default reload cost"><input type="number" min="0" value={form.defaultReloadCost} onChange={(e) => set('defaultReloadCost', e.target.value)} className={input} placeholder="3500" /></Field>
    <Field label="Default validity"><input value={form.defaultReloadValidity} onChange={(e) => set('defaultReloadValidity', e.target.value)} className={input} placeholder="30Days" /></Field>
    <Field label="Expires after days"><input type="number" min="0" value={form.defaultReloadExpiresAfterDays} onChange={(e) => set('defaultReloadExpiresAfterDays', e.target.value)} className={input} /></Field>
    {initial?.id && <Field label="Manual SIM balance (MB)"><input type="number" min="0" value={form.simBalance} onChange={(e) => set('simBalance', e.target.value)} className={input} /></Field>}
    <div className="sm:col-span-2"><Field label="Note"><textarea value={form.note} onChange={(e) => set('note', e.target.value)} className={input} rows="2" /></Field></div>
  </div>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-gray-200 px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-orange-500 px-5 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save SIM'}</button></div></form>;
}

function BatchForm({ sims, initial, onSubmit, onClose }) {
  const [form, setForm] = useState({ ...BATCH_EMPTY, ...initial }); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { const allowed = initial?.id ? ['validity','expiresAt','status','note'] : ['dataShareSimId','totalData','totalCost','validity','expiresAt','status','note']; const body = Object.fromEntries(allowed.filter((key) => form[key] !== '').map((key) => [key, key === 'totalCost' ? Number(form[key]) : form[key]])); await onSubmit(body); onClose(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  return <form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2">
    {!initial?.id && <Field label="DataShare SIM *"><select required value={form.dataShareSimId} onChange={(e) => setForm({...form,dataShareSimId:e.target.value})} className={input}><option value="">Select SIM</option>{sims.map((sim) => <option key={sim.id} value={sim.id}>{sim.label || sim.phoneNumber} — {sim.phoneNumber}</option>)}</select></Field>}
    {!initial?.id && <Field label="Total data *"><input required value={form.totalData} onChange={(e) => setForm({...form,totalData:e.target.value})} className={input} placeholder="10GB" /></Field>}
    {!initial?.id && <Field label="Total cost *"><input required type="number" min="0" value={form.totalCost} onChange={(e) => setForm({...form,totalCost:e.target.value})} className={input} /></Field>}
    <Field label="Validity"><input value={form.validity ?? ''} onChange={(e) => setForm({...form,validity:e.target.value})} className={input} placeholder="30Days" /></Field>
    <Field label="Status"><select value={form.status} onChange={(e) => setForm({...form,status:e.target.value})} className={input}><option>active</option><option>exhausted</option><option>expired</option><option>disabled</option></select></Field>
    <Field label="Expires at"><input type="datetime-local" value={form.expiresAt?.slice?.(0,16) ?? ''} onChange={(e) => setForm({...form,expiresAt:e.target.value})} className={input} /></Field>
    <div className="sm:col-span-2"><Field label="Note"><textarea value={form.note ?? ''} onChange={(e) => setForm({...form,note:e.target.value})} className={input} rows="2" /></Field></div>
  </div>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-gray-200 px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-orange-500 px-5 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Saving…' : initial?.id ? 'Update stock' : 'Add stock'}</button></div></form>;
}

function AdjustBatchForm({ batch, onSubmit, onClose }) {
  const [form, setForm] = useState({ direction: 'reduce', adjustmentData: '', adjustmentMb: '', costAdjustment: '' });
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const set = (key, value) => setForm((old) => ({ ...old, [key]: value }));
  async function submit(e) {
    e.preventDefault(); setError('');
    if (!form.adjustmentData && form.adjustmentMb === '') { setError('Enter an adjustment in data units or MB.'); return; }
    setSaving(true);
    try {
      const body = { direction: form.direction };
      if (form.adjustmentData) body.adjustmentData = form.adjustmentData;
      else body.adjustmentMb = Number(form.adjustmentMb);
      if (form.costAdjustment !== '') body.costAdjustment = Number(form.costAdjustment);
      await onSubmit(body); onClose();
    } catch (err) { setError(err.message); } finally { setSaving(false); }
  }
  return <form onSubmit={submit}>
    <div className="mb-5 rounded-xl border border-gray-200 bg-gray-50 p-4 text-sm text-gray-600"><p className="font-semibold text-gray-900">{batch.simPhoneNumber ?? batch.phoneNumber ?? 'Stock batch'}</p><p className="mt-1">Remaining: <span className="font-semibold text-orange-600">{compact(batch.remaining)}</span> of {compact(batch.total)}</p></div>
    <div className="grid gap-4 sm:grid-cols-2">
      <Field label="Direction *"><select required value={form.direction} onChange={(e) => set('direction', e.target.value)} className={input}><option value="reduce">Reduce stock</option><option value="add">Add stock</option></select></Field>
      <Field label="Adjustment data"><input value={form.adjustmentData} onChange={(e) => { set('adjustmentData', e.target.value); if (e.target.value) set('adjustmentMb', ''); }} className={input} placeholder="500MB, 1GB, 2.5GB" /></Field>
      <Field label="Or adjustment (MB)"><input type="number" min="0.01" step="any" value={form.adjustmentMb} onChange={(e) => { set('adjustmentMb', e.target.value); if (e.target.value) set('adjustmentData', ''); }} className={input} placeholder="500" /></Field>
      <Field label="Cost adjustment (optional)"><input type="number" step="any" value={form.costAdjustment} onChange={(e) => set('costAdjustment', e.target.value)} className={input} placeholder="Negative values subtract" /></Field>
    </div>
    <p className="mt-4 text-xs text-gray-500">Reductions cannot exceed unused stock. The optional cost adjustment changes the batch's total cost.</p>
    {error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-gray-200 px-4 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-lg bg-orange-500 px-5 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Adjusting…' : 'Apply adjustment'}</button></div>
  </form>;
}

function DeleteBatchForm({ batch, onDelete, onClose }) {
  const [deleting, setDeleting] = useState(false); const [error, setError] = useState('');
  const hasSales = Number(batch.soldMb ?? 0) > 0;
  async function remove() { setDeleting(true); setError(''); try { await onDelete(); onClose(); } catch (err) { setError(err.message); } finally { setDeleting(false); } }
  return <div><div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p className="font-semibold">This permanently deletes the mistaken stock load.</p><p className="mt-2">Deletion succeeds only when no stock has been sold and no usage records are linked to this batch.</p></div><div className="mt-4 rounded-xl border border-gray-200 p-4 text-sm"><p className="font-semibold text-gray-900">{batch.simPhoneNumber ?? batch.phoneNumber ?? 'Stock batch'}</p><p className="mt-1 text-gray-500">Loaded: {compact(batch.total)} · Remaining: {compact(batch.remaining)}</p></div>{hasSales && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">This batch has sold stock and cannot be deleted. Edit its status to <strong>disabled</strong> instead.</p>}{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border border-gray-200 px-4 py-2 text-sm">Cancel</button><button type="button" disabled={deleting || hasSales} onClick={remove} className="rounded-lg bg-red-600 px-5 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{deleting ? 'Deleting…' : 'Delete stock'}</button></div></div>;
}

export default function DataShare() {
  const api = useDataShare(); const [tab, setTab] = useState('sims'); const [modal, setModal] = useState(null); const [notice, setNotice] = useState(''); const [actionError, setActionError] = useState('');
  const [filters, setFilters] = useState({ status: '', groupName: '', phoneNumber: '', simPhoneNumber: '', reference: '' });
  const summary = api.summary ?? {}; const exceptions = Number(summary.unmatchedCount ?? 0);
  const orderedBatches = useMemo(() => [...api.batches].sort((a,b) => (a.status === 'active' ? 0 : 1) - (b.status === 'active' ? 0 : 1)), [api.batches]);
  async function reload(sim) { if (!window.confirm(`Add a stock batch to ${sim.label || sim.phoneNumber} using its saved reload defaults?`)) return; setActionError(''); try { await api.reloadSim(sim.id); setNotice(`${sim.label || sim.phoneNumber} reloaded successfully.`); } catch (err) { setActionError(err.message); } }
  async function search(e) { e.preventDefault(); const clean = (values) => Object.fromEntries(Object.entries(values).filter(([,v]) => v)); if (tab === 'sims') await api.loadSims(clean({ status: filters.status, groupName: filters.groupName, phoneNumber: filters.phoneNumber })); if (tab === 'stock') await api.loadBatches(clean({ status: filters.status, groupName: filters.groupName, simPhoneNumber: filters.simPhoneNumber })); if (tab === 'usage') await api.loadUsages(clean({ status: filters.status, simPhoneNumber: filters.simPhoneNumber, reference: filters.reference })); }
  const cards = [{ label:'Active SIMs', value:summary.activeSimCount ?? 0 },{ label:'Total stock', value:summary.total ?? '0GB' },{ label:'Stock remaining', value:summary.remaining ?? '0GB' },{ label:'Sold', value:summary.sold ?? '0GB' },{ label:'Revenue', value:money(summary.revenue) },{ label:'Profit', value:money(summary.profit), green:true },{ label:'Unmatched usage', value:exceptions, alert:exceptions > 0 }];
  return <div>
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2"><span className="rounded-full bg-yellow-300 px-2.5 py-1 text-xs font-black text-slate-900">MTN</span><span className="text-xs font-semibold uppercase tracking-widest text-gray-400">DataShare</span></div><h1 className="text-2xl font-bold text-gray-900">DataShare inventory</h1><p className="mt-1 text-sm text-gray-500">Monitor SIM capacity, stock batches, limits, and transaction profitability.</p></div><div className="flex gap-2"><button onClick={api.refresh} disabled={api.loading} className="rounded-lg border border-gray-200 bg-white px-4 py-2 text-sm font-semibold text-gray-600">↻ Refresh</button><button onClick={() => setModal({type:'sim'})} className="rounded-lg bg-orange-500 px-4 py-2 text-sm font-semibold text-white">+ Add SIM</button><button onClick={() => setModal({type:'batch'})} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-slate-900">+ Add stock</button></div></div>
    {(api.error || actionError) && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{api.error || actionError}</div>}{notice && <div className="mb-5 flex justify-between rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700"><span>{notice}</span><button onClick={() => setNotice('')}>✕</button></div>}
    <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-7">{cards.map((card) => <div key={card.label} className={`rounded-xl border bg-white p-4 shadow-sm ${card.alert ? 'border-red-300 ring-2 ring-red-100' : 'border-gray-200'}`}><p className="text-[11px] font-bold uppercase tracking-wide text-gray-400">{card.label}</p><p className={`mt-2 text-xl font-bold ${card.alert ? 'text-red-600' : card.green ? 'text-emerald-600' : 'text-gray-900'}`}>{card.value}</p>{card.alert && <button onClick={() => setTab('usage')} className="mt-1 text-xs font-semibold text-red-600 underline">Review now</button>}</div>)}</div>
    <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div className="flex border-b border-gray-200 px-4">{[['sims',`SIMs (${api.counts.sims})`],['stock',`Stock (${api.counts.batches})`],['usage',`Usage (${api.counts.usages})`]].map(([key,label]) => <button key={key} onClick={() => {setTab(key);setFilters({ status:'',groupName:'',phoneNumber:'',simPhoneNumber:'',reference:'' });}} className={`border-b-2 px-4 py-4 text-sm font-semibold ${tab === key ? 'border-orange-500 text-orange-600' : 'border-transparent text-gray-500'}`}>{label}</button>)}</div>
      <form onSubmit={search} className="flex flex-wrap gap-2 border-b border-gray-100 bg-gray-50 p-4"><select value={filters.status} onChange={(e)=>setFilters({...filters,status:e.target.value})} className={input+' w-40'}><option value="">All statuses</option>{(tab==='sims'?['active','paused','retired']:tab==='stock'?['active','exhausted','expired','disabled']:['matched','unmatched','lookup_failed']).map(x=><option key={x}>{x}</option>)}</select>{tab !== 'usage' && <input value={filters.groupName} onChange={(e)=>setFilters({...filters,groupName:e.target.value})} className={input+' w-40'} placeholder="Group name" />}{tab === 'sims' ? <input value={filters.phoneNumber} onChange={(e)=>setFilters({...filters,phoneNumber:e.target.value})} className={input+' w-52'} placeholder="Phone number" /> : <input value={filters.simPhoneNumber} onChange={(e)=>setFilters({...filters,simPhoneNumber:e.target.value})} className={input+' w-52'} placeholder="SIM phone number" />}{tab === 'usage' && <input value={filters.reference} onChange={(e)=>setFilters({...filters,reference:e.target.value})} className={input+' w-52'} placeholder="Reference" />}<button className="rounded-lg bg-orange-500 px-4 py-2 text-sm font-semibold text-white">Filter</button></form>
      {api.loading ? <div className="py-24 text-center text-sm text-gray-400">Loading DataShare inventory…</div> : <div className="overflow-x-auto">
        {tab === 'sims' && <table className="w-full min-w-[1450px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{['SIM','Group / rotation','Internal stock','Provider balance','Daily data used','Monthly slots','Financials','Status','Actions'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{api.sims.map(sim=><tr key={sim.id} className="hover:bg-gray-50"><td className="px-4 py-4"><p className="font-semibold text-gray-900">{sim.label || 'Unnamed SIM'}</p><p className="font-mono text-xs text-gray-500">{sim.phoneNumber}</p></td><td className="px-4 py-4"><p>{compact(sim.groupName)}</p><p className="text-xs text-gray-400">Days {compact(sim.activeFromDay)}–{compact(sim.activeToDay)}</p></td><td className="px-4 py-4"><p className="font-bold text-gray-900">{compact(sim.remaining)}</p><p className="text-xs text-gray-400">of {compact(sim.total)}</p></td><td className="px-4 py-4"><p className="font-bold text-blue-600">{compact(sim.simBalance)}</p><p className="text-xs text-gray-400">{sim.lastProviderReportedAt ? `Updated ${date(sim.lastProviderReportedAt)}` : 'Not reported'}</p></td><td className="px-4 py-4"><Progress value={sim.todaySharedMb} max={sim.dailyLimitMb} warning={sim.dailyLimitReached}/><p className="mt-1 text-xs text-gray-400">{compact(sim.todayShared)} shared · {sim.todayShareCount ?? 0} vends</p></td><td className="px-4 py-4"><Progress value={sim.monthShareCount} max={sim.monthlyShareLimit} warning={sim.monthlyLimitReached}/><p className="mt-1 text-xs text-gray-400">{sim.monthlyRemainingShareSlots ?? 0} slots left</p></td><td className="px-4 py-4"><p className="font-semibold text-emerald-600">{money(sim.profit)} profit</p><p className="text-xs text-gray-400">{money(sim.revenue)} revenue</p></td><td className="px-4 py-4"><Badge value={sim.status}/></td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={()=>setModal({type:'sim',item:sim})} className="rounded-lg border border-gray-200 px-3 py-1.5 text-xs font-semibold">Edit</button><button disabled={!sim.canQuickReload} onClick={()=>reload(sim)} title={!sim.canQuickReload?'Save reload defaults first':''} className="rounded-lg bg-orange-50 px-3 py-1.5 text-xs font-semibold text-orange-700 disabled:opacity-40">Quick reload</button></div></td></tr>)}</tbody></table>}
        {tab === 'stock' && <table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{['SIM','Group','Loaded','Remaining','Cost','Revenue','Profit','Validity / expiry','Status','Actions'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{orderedBatches.map(batch=><tr key={batch.id} className="hover:bg-gray-50"><td className="px-4 py-4 font-mono text-xs">{batch.simPhoneNumber ?? batch.phoneNumber ?? '—'}</td><td className="px-4 py-4">{compact(batch.groupName)}</td><td className="px-4 py-4 font-semibold">{compact(batch.total)}</td><td className="px-4 py-4 font-bold text-orange-600">{compact(batch.remaining)}</td><td className="px-4 py-4">{money(batch.totalCost)}</td><td className="px-4 py-4">{money(batch.revenue)}</td><td className="px-4 py-4 font-semibold text-emerald-600">{money(batch.profit)}</td><td className="px-4 py-4"><p>{compact(batch.validity)}</p><p className="text-xs text-gray-400">{date(batch.expiresAt)}</p></td><td className="px-4 py-4"><Badge value={batch.status}/></td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={()=>setModal({type:'batch',item:batch})} className="rounded-lg border border-gray-200 px-3 py-1.5 text-xs font-semibold">Edit</button><button onClick={()=>setModal({type:'adjust',item:batch})} className="rounded-lg bg-orange-50 px-3 py-1.5 text-xs font-semibold text-orange-700">Adjust</button><button onClick={()=>setModal({type:'delete',item:batch})} className="rounded-lg bg-red-50 px-3 py-1.5 text-xs font-semibold text-red-700">Delete</button></div></td></tr>)}</tbody></table>}
        {tab === 'usage' && <table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{['Status','Reference','Sender SIM','Recipient','Data','Cost','Revenue','Profit','Created'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{[...api.usages].sort((a,b)=>(a.status==='matched'?1:0)-(b.status==='matched'?1:0)).map(usage=><tr key={usage.id ?? usage.reference} className={usage.status !== 'matched' ? 'bg-red-50/40' : 'hover:bg-gray-50'}><td className="px-4 py-4"><Badge value={usage.status}/></td><td className="px-4 py-4 font-mono text-xs">{compact(usage.reference)}</td><td className="px-4 py-4 font-mono text-xs">{compact(usage.simPhoneNumber ?? usage.senderPhoneNumber)}</td><td className="px-4 py-4">{compact(usage.recipientPhoneNumber ?? usage.phoneNumber)}</td><td className="px-4 py-4 font-semibold">{compact(usage.data ?? usage.sold ?? (usage.soldMb ? `${usage.soldMb}MB` : null))}</td><td className="px-4 py-4">{money(usage.costSpent ?? usage.cost)}</td><td className="px-4 py-4">{money(usage.revenue)}</td><td className="px-4 py-4 font-semibold text-emerald-600">{money(usage.profit)}</td><td className="px-4 py-4 text-xs text-gray-500">{date(usage.createdAt)}</td></tr>)}</tbody></table>}
        {((tab==='sims'&&!api.sims.length)||(tab==='stock'&&!api.batches.length)||(tab==='usage'&&!api.usages.length)) && <div className="py-20 text-center text-sm text-gray-400">No {tab} records found.</div>}
      </div>}
    </div>
    {modal?.type === 'sim' && <Modal title={modal.item ? 'Edit DataShare SIM' : 'Add DataShare SIM'} onClose={()=>setModal(null)}><SimForm initial={modal.item} onClose={()=>setModal(null)} onSubmit={(body)=>modal.item ? api.updateSim(modal.item.id, body) : api.createSim(body)} /></Modal>}
    {modal?.type === 'batch' && <Modal title={modal.item ? 'Edit stock batch' : 'Add DataShare stock'} onClose={()=>setModal(null)}><BatchForm sims={api.sims} initial={modal.item} onClose={()=>setModal(null)} onSubmit={(body)=>modal.item ? api.updateBatch(modal.item.id, body) : api.createBatch(body)} /></Modal>}
    {modal?.type === 'adjust' && <Modal title="Adjust DataShare stock" onClose={()=>setModal(null)}><AdjustBatchForm batch={modal.item} onClose={()=>setModal(null)} onSubmit={(body)=>api.adjustBatch(modal.item.id, body)} /></Modal>}
    {modal?.type === 'delete' && <Modal title="Delete DataShare stock" onClose={()=>setModal(null)}><DeleteBatchForm batch={modal.item} onClose={()=>setModal(null)} onDelete={()=>api.deleteBatch(modal.item.id)} /></Modal>}
  </div>;
}
